services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: grafana-labs-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "5140:9090"

  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana-labs-grafana
    ports:
      - "5150:3000"
